### ISSUE TITLE
OutOfMemory Error

### ISSUE THREAD

**Issue by ismdcf** [aellerton/japng_android#1]
When I try to use this library with a custom apng file I get this Error

`Process: net.ellerton.japng.android.demo, PID: 26897
                                                                                 java.lang.OutOfMemoryError
                                                                                     at android.graphics.Bitmap.nativeCopy(Native Method)
  at android.graphics.Bitmap.nativeCopy(Native Method)
                                                                                     at android.graphics.Bitmap.copy(Bitmap.java:556)
                                                                                     at net.ellerton.japng.android.api.PngAnimationComposer.completeFrame(PngAnimationComposer.java:148)
                                                                                     at net.ellerton.japng.android.api.PngViewBuilder.receiveFrameImage(PngViewBuilder.java:94)
                                                                                     at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:153)
                                                                                     at net.ellerton.japng.reader.DefaultPngChunkReader.readFrameImageDataChunk(DefaultPngChunkReader.java:254)
                                                                                     at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:78)
                                                                                     at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
                                                                                     at net.ellerton.japng.android.api.PngAndroid.readDrawable(PngAndroid.java:29)
                                                                                     at net.ellerton.japng.android.demo.PngViewActivity.getComposedAnimation(PngViewActivity.java:169)
                                                                                     at net.ellerton.japng.android.demo.view.ViewTabsFragment.onViewCreated(ViewTabsFragment.java:135)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                                                     at android.app.Activity.performStart(Activity.java:5240)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by aellerton** [comment]
Thanks for filing. Can you attach or link to the image?

**Comment by aellerton** [comment]
@ismdcf did you solve this? I'm looking at closing this issue if it can't be reproduced.
