### ISSUE TITLE
Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference

### ISSUE THREAD

**Issue by jndefosse** [aellerton/japng_android#4]
Hello

Thanks for your librairy, it's very usefull

I saw you have fixed a bug on Java project but not in the Android, can you fix-it?

I have the same bug as
https://github.com/aellerton/japng/issues/2

FATAL EXCEPTION: main
                                                                                 Process: net.ellerton.japng.android.demo, PID: 17520
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ellerton.japng.android.demo/net.ellerton.japng.android.demo.PngViewActivity}: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
                                                                                     at net.ellerton.japng.argb8888.Argb8888Processors$IndexedColour8.processScanline(Argb8888Processors.java:168)
                                                                                     at net.ellerton.japng.PngScanlineBuffer.decompress(PngScanlineBuffer.java:112)
                                                                                     at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:151)
                                                                                     at net.ellerton.japng.reader.DefaultPngChunkReader.readImageDataChunk(DefaultPngChunkReader.java:175)
                                                                                     at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:66)
                                                                                     at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
                                                                                     at net.ellerton.japng.android.api.PngAndroid.readDrawable(PngAndroid.java:29)
                                                                                     at net.ellerton.japng.android.demo.PngViewActivity.getComposedAnimation(PngViewActivity.java:169)
                                                                                     at net.ellerton.japng.android.demo.view.ViewTabsFragment.onViewCreated(ViewTabsFragment.java:135)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1010)
                                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                                     at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                                                                                     at android.app.Activity.performStart(Activity.java:6695)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by vicktorial** [comment]
Hello
I also have the same bug as
Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference

**Comment by aellerton** [comment]
@vicktorial Can you please outline steps to reproduce, including a specific PNG file if you have one.

I'll be integrating contributed patches soon - I'm a bit behind at the moment.

**Comment by vicktorial** [comment]
Hello
This is my log
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.ellerton.japng.android.demo/net.ellerton.japng.android.demo.TestActivity}: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                      at android.app.ActivityThread.access$800(ActivityThread.java:144)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                   Caused by: java.lang.NullPointerException: Attempt to read from field 'int[] net.ellerton.japng.argb8888.Argb8888Palette.argbArray' on a null object reference
                      at net.ellerton.japng.argb8888.Argb8888Processors$IndexedColour8.processScanline(Argb8888Processors.java:168)
                      at net.ellerton.japng.PngScanlineBuffer.decompress(PngScanlineBuffer.java:112)
                      at net.ellerton.japng.argb8888.Argb8888Processor.processFrameImageData(Argb8888Processor.java:151)
                      at net.ellerton.japng.reader.DefaultPngChunkReader.readImageDataChunk(DefaultPngChunkReader.java:175)
                      at net.ellerton.japng.reader.DefaultPngChunkReader.readChunk(DefaultPngChunkReader.java:66)
                      at net.ellerton.japng.reader.PngReadHelper.read(PngReadHelper.java:63)
                      at net.ellerton.japng.android.api.PngAndroid.readDrawable(PngAndroid.java:29)
                      at net.ellerton.japng.android.api.PngAndroid.readDrawable(PngAndroid.java:38)
                      at net.ellerton.japng.android.demo.TestActivity.getComposedAnimation(TestActivity.java:67)
                      at net.ellerton.japng.android.demo.TestActivity.onCreate(TestActivity.java:40)
                      at android.app.Activity.performCreate(Activity.java:5933)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5221) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 

This is my code:
mDrawable = composedAnimation = PngAndroid.readDrawable(this, R.raw.apng_geneva_drive);
`mImageView.setImageDrawable(mDrawable);

Only this one picture 
![image](https://cloud.githubusercontent.com/assets/10985807/25648373/b1c3f54c-2ffd-11e7-9327-0a406ceefde4.png)

**Comment by vicktorial** [comment]
I can not upload the picture.

**Comment by jhyHenry** [comment]
I have the same error，I use tinypng compress apng，then occur the bug。can you fix-it? thx
